# Generated by Django 3.0.6 on 2020-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='record/2020/05/25'),
        ),
    ]
