# Generated by Django 3.0.6 on 2020-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200525_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='record/2020/05/28'),
        ),
    ]
